version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore'
    ignore:
      - dependency-name: '@types/node'
    groups:
      lint:
        patterns:
          - 'eslint*'
          - 'prettier'
          - 'husky'
          - 'lint-staged'
          - '@typescript-eslint*'
