version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit_message:
      prefix: 'chore'
      include_scope: false

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit_message:
      prefix: 'chore'
      include_scope: false
