name: 'PR Title Verify'
description: 'Check PR title against a regex'
author: 'Satvik Shukla'
inputs:
  pattern:
    required: false
    description: 'regex pattern to match against'
  flags:
    required: false
    description: 'flags for the regex input'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check'
  color: 'blue'
